### ISSUE TITLE
Failed to add geofence: com.google.android.gms.common.api.ApiException: 1004:

### ISSUE THREAD

**Issue by JuniorEC** [bkonyi/FlutterGeofencing#72]
I added geofence in my app similar to the example in this repository and I'm getting the following error:
`
W/ConnectionTracker( 7947): Exception thrown while unbinding
W/ConnectionTracker( 7947): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@84ae46d
W/ConnectionTracker( 7947): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
W/ConnectionTracker( 7947): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
W/ConnectionTracker( 7947): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
W/ConnectionTracker( 7947): 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker( 7947): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker( 7947): 	at com.google.android.gms.measurement.internal.zzio.zzag(com.google.android.gms:play-services-measurement-impl@@17.6.0:245)
W/ConnectionTracker( 7947): 	at com.google.android.gms.measurement.internal.zzio.zzal(com.google.android.gms:play-services-measurement-impl@@17.6.0:262)
W/ConnectionTracker( 7947): 	at com.google.android.gms.measurement.internal.zzio.zzc(com.google.android.gms:play-services-measurement-impl@@17.6.0:336)
W/ConnectionTracker( 7947): 	at com.google.android.gms.measurement.internal.zzir.zza(com.google.android.gms:play-services-measurement-impl@@17.6.0:2)
`

My AndroidManifest:
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.jdjtechnology.rh_manager">
  

  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

  <application android:name="io.flutter.app.FlutterApplication" android:label="rh_manager" android:icon="@mipmap/ic_launcher">

    <meta-data android:name="com.google.android.geo.API_KEY" android:value="0000000000000000000000000" />

    <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
      
      <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
      
      <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    
    <meta-data android:name="flutterEmbedding" android:value="2" />
    <receiver android:name="io.flutter.plugins.geofencing.GeofencingBroadcastReceiver" android:enabled="true" android:exported="true" />
    <receiver android:name="io.flutter.plugins.geofencing.GeofencingRebootBroadcastReceiver" android:enabled="true">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"></action>
      </intent-filter>
    </receiver>
    <service android:name="io.flutter.plugins.geofencing.GeofencingService" android:exported="true" android:permission="android.permission.BIND_JOB_SERVICE" />
  </application>
</manifest>

`

Flutter doctor:
`
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [versÃ£o 10.0.18363.1198], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.51.1)
[√] Connected device (1 available)
`

**Comment by DevarshRanpara** [comment]
Hi @JuniorEC ,
I was having same issues.
Error code 1004 mens app does not have enough permissions to operate, and that's why you are having that issue.
For refrence check [this](https://developers.google.com/android/reference/com/google/android/gms/location/GeofenceStatusCodes) out.
You will need to add `<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>` permission in your app.
You can use `location_permissions` plugin to get location permissions.
Make sure your app have background location permission.

**Comment by stoxxy** [comment]
It's kind of strange that the Geofence API requires access to location in the background while not working in the background at all
